### PR TITLE
Created the Projects page

### PR DESCRIPTION
**Pull request by Plvtinum-1**
# Features #98  #

### Additional Screenshots

Projects Section
Navigation

### Checklist

- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/snapitsolutions/snapit-hacktoberfest/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests and/or screenshots that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

### CODE REVIEW

**Review by camitaylor — DISMISSED** [review]
Your branch has conflicts that need to be resolved due to a PR that was merged earlier.  It is also not passing 2 of the checks.

**Comment by Plvtinum-1** [comment]
It looks like vite couldn't find the @mui/styles package, this is the error message I got
```
[vite]: Rollup failed to resolve import "@mui/styles" from "src/pages/Projects/styles.js".
```
Can anyone help me solve this issue? thanks.

**Comment by Plvtinum-1** [comment]
Hello could you try to merge this pull request please?

**Comment by dylhack** [comment]
I'm not able to reproduce the issue, can you give me your node, npm, and vite version?  Like so:
```
$ vite --version
vite/2.6.10 linux-x64 node-v14.18.1
$ node --version
v14.18.1
$ npm --version
8.1.0
```

**Pull request merged**
